---
title: "total_stats"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(data.table)
library(ggplot2)
library(scales)
library(sp)
library(corrplot)
library(ggpubr)
library(ggrepel)
```

```{r, echo = FALSE}
#this chunk puts all of the data from persons.csv and genderize_results.json into the dataframe "data" (i know, it's a horrible name)
josh_pc_data <-read.csv("graphable_joshpc.csv", na.strings=c(" "))
josh_laptop_data <-read.csv("graphable_laptop.csv", na.strings=c(" "))
ryan_macbook_data <-read.csv("graphable_ryanmacbook.csv", na.strings=c(" "))
```

```{r, echo = FALSE}
#general
josh_pc_time =(josh_pc_data[,1])
josh_pc_size =(josh_pc_data[,2])
josh_laptop_time =(josh_laptop_data[,1])
josh_laptop_size =(josh_laptop_data[,2])
ryan_macbook_time =(ryan_macbook_data[,1])
ryan_macbook_size =(ryan_macbook_data[,2])

josh_pc_time2 = round(josh_pc_time)
josh_pc_size = josh_pc_size/1024
josh_pc_h = c(7,9,11)

josh_laptop_time2 = round(josh_laptop_time)
josh_laptop_size = josh_laptop_size/1024
josh_laptop_h = c(7,9,11)

ryan_macbook_time2 = round(ryan_macbook_time)
ryan_macbook_size = ryan_macbook_size/1024
ryan_macbook_h = c(7,9,11)

plotdata = data.frame(josh_pc_size,josh_pc_time)
outplot <- ggplot(data = plotdata, aes(x = josh_pc_size, y= josh_pc_time, group = 1)) + geom_line(colour = "red") + geom_point(colour = "black") + geom_point(data = plotdata[h,], aes(x = josh_pc_size, y= josh_pc_time), colour = "blue") + labs(title="Graph of Time per Access as a Function of Buffer Size", x ="Buffer Size (KB)", y = "Time per Access (ns)") + xscale("log2", .format = TRUE) + geom_label_repel(aes(label = josh_pc_time2), box.padding   = 0.8, point.padding = 0.3, direction = "y", segment.color = 'grey50')
outplot
ggsave("final_plot.png", limitsize = FALSE)
```